name: Deploy React Frontend to ECR

on:
  schedule:
    - cron: '40 23 * * *'
  push:
    branches:
      - main

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[build]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
          yarn add --dev @testing-library/react @testing-library/jest-dom @testing-library/dom

      - name: Run Tests
        run: yarn test --watchAll=false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Determine Version
        id: get_version
        run: |
          VERSION=$(date -u +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Multi-Arch Docker Image
        env:
          REPO_URI: 428300362017.dkr.ecr.us-east-1.amazonaws.com/supreme-showcase-frontend
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} \
            --tag $REPO_URI:$VERSION \
            --tag $REPO_URI:latest \
            --push .
